name: Build and Test

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.0
        env:
          # Build configuration
          CIBW_BUILD: cp310-* cp311-* cp312-*
          CIBW_SKIP: "*-win32"
          
          CIBW_BEFORE_ALL_LINUX: |
            yum install -y boost-devel || apt-get update && apt-get install -y libboost-all-dev
          
          CIBW_BEFORE_ALL_WINDOWS: |
            C:\vcpkg\vcpkg integrate install &&
            C:\vcpkg\vcpkg install boost-interprocess
          
          CIBW_TEST_REQUIRES: pytest numpy
          CIBW_TEST_COMMAND: python -m pytest -v

        with:
          package-dir: .
          output-dir: wheelhouse

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl