name: Build and Test

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    VCPKG_INSTALLATION_ROOT: C:\vcpkg

jobs:
  build_and_test:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
    
      - name: Install boost on Windows
        if: runner.os == 'Windows'
        run: |
          ${{ env.VCPKG_INSTALLATION_ROOT }}\vcpkg install boost-interprocess
      - name: Install boost on Linux
        if: runner.os == 'Linux'
        run: |
            sudo apt update && sudo apt install -y libboost-all-dev
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.0
        env:
          # Build configuration
          CIBW_BUILD: cp310-* cp311-* cp312-*
          CIBW_SKIP: "*-win32"

          CIBW_TEST_REQUIRES: pytest numpy
          CIBW_TEST_COMMAND: python -m pytest -v

        with:
          package-dir: .
          output-dir: wheelhouse

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl