name: Build and Test

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev

      - name: Install system dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          # Install vcpkg and boost for Windows
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg integrate install
          ./vcpkg install boost:x64-windows
        shell: cmd

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.0
        env:
          # Build configuration
          CIBW_BUILD: cp310-* cp311-* cp312-*
          CIBW_SKIP: "*-win32 pp*"
          
          # Linux-specific settings
          CIBW_BEFORE_ALL_LINUX: |
            yum install -y boost-devel || apt-get update && apt-get install -y libboost-all-dev
          
          # Windows-specific settings
          CIBW_BEFORE_ALL_WINDOWS: |
            git clone https://github.com/microsoft/vcpkg.git C:\vcpkg &&
            C:\vcpkg\bootstrap-vcpkg.bat &&
            C:\vcpkg\vcpkg install boost-interprocess
          
          # Test command to run after building each wheel
          CIBW_TEST_REQUIRES: pytest numpy
          CIBW_TEST_COMMAND: python -m pytest -v

        with:
          package-dir: .
          output-dir: wheelhouse

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl